{% set version = '0.8.8' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsconnect
  version: {{ version|replace("-", "_") }}

source:
  fn: rsconnect_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/rsconnect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsconnect/rsconnect_{{ version }}.tar.gz
  sha256: 91825eca63172ed0d36f02a8db9c4e0a44188bb01af8341558398a5715873705

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-pki
    - r-rcurl
    - r-rjsonio
    - r-digest
    - r-packrat >=0.4.8_1
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5
  run:
    - r-base
    - r-pki
    - r-rcurl
    - r-rjsonio
    - r-digest
    - r-packrat >=0.4.8_1
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5

test:
  commands:
    - $R -e "library('rsconnect')"           # [not win]
    - "\"%R%\" -e \"library('rsconnect')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsconnect
  license: GPL-2
  summary: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'RStudio Connect'.
    Supported content types include R Markdown documents, Shiny applications, Plumber
    APIs, plots, and static web content.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-2'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
