{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rsconnect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsconnect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsconnect/rsconnect_{{ version }}.tar.gz
  sha256: 769c5bd4092c665dfb4fcc086be72579546ff1fbe674747c25dd370651dc9aa8

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-curl
    - r-digest
    - r-jsonlite
    - r-openssl
    - r-packrat >=0.5
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5
  run:
    - r-base
    - r-curl
    - r-digest
    - r-jsonlite
    - r-openssl
    - r-packrat >=0.5
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5

test:
  commands:
    - $R -e "library('rsconnect')"           # [not win]
    - "\"%R%\" -e \"library('rsconnect')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=rsconnect
  license: GPL-2.0-only
  summary: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'RStudio Connect'. Supported content types include R Markdown documents, Shiny applications, Plumber APIs, plots, and static web content.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: rsconnect
# Type: Package
# Title: Deployment Interface for R Markdown Documents and Shiny Applications
# Version: 0.8.15
# Author: JJ Allaire
# Maintainer: Jonathan McPherson <jonathan@rstudio.com>
# Description: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'RStudio Connect'. Supported content types include R Markdown documents, Shiny applications, Plumber APIs, plots, and static web content.
# Depends: R (>= 3.0.0)
# Imports: curl, jsonlite, openssl, packrat (>= 0.4.8-1), rstudioapi (>= 0.5), yaml (>= 2.1.5)
# Suggests: RCurl, callr, httpuv, knitr, plumber (>= 0.3.2), reticulate, rmarkdown (>= 1.1), shiny, sourcetools, testthat, xtable
# License: GPL-2
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-07-22 21:53:14 UTC; jmcphers
# Repository: CRAN
# Date/Publication: 2019-07-22 22:50:02 UTC
