{% set version = "1.3.2" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rsconnect
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rsconnect_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rsconnect/rsconnect_{{ version }}.tar.gz
  sha256: c6e1a05461e1129aa4ab6016a466dd771b949fa1be62b018109be990533d0555

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-pki
    - r-cli
    - r-curl
    - r-digest
    - r-jsonlite
    - r-lifecycle
    - r-openssl >=2.0.0
    - r-packrat >=0.6
    - r-renv >=1.0.0
    - r-rlang >=1.0.0
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5
  run:
    - r-base
    - r-pki
    - r-cli
    - r-curl
    - r-digest
    - r-jsonlite
    - r-lifecycle
    - r-openssl >=2.0.0
    - r-packrat >=0.6
    - r-renv >=1.0.0
    - r-rlang >=1.0.0
    - r-rstudioapi >=0.5
    - r-yaml >=2.1.5

test:
  commands:
    - $R -e "library('rsconnect')"           # [not win]
    - "\"%R%\" -e \"library('rsconnect')\""  # [win]

about:
  home: https://github.com/rstudio/rsconnect
  license: GPL-2.0-only
  summary: Programmatic deployment interface for 'RPubs', 'shinyapps.io', and 'Posit Connect'. Supported content types include R Markdown documents, Shiny applications, Plumber APIs, plots, and static web content.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
